apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    jsonData:
      index: 'biometrics-*'
      timeField: '@timestamp'
      esVersion: '8.13.4'

  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: suenoia
    user: suenoia
    isDefault: true
    secureJsonData:
      password: suenoia_pass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true
