# SueñoIA Mosquitto config (modo dev)

# Persistencia de mensajes
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type all
log_timestamp true

# MQTT estándar
listener 1883
allow_anonymous true

# MQTT sobre WebSocket (para que el frontend pueda subscribirse directo)
listener 9001
protocol websockets
allow_anonymous true
